#!/bin/bash
# Quick fix script for MongoDB connection issue

echo "🔧 MongoDB Connection Fix"
echo "========================="
echo ""
echo "Your MongoDB Atlas cluster is blocking your IP address."
echo ""
echo "Choose a solution:"
echo ""
echo "Option 1: Fix MongoDB Atlas IP Whitelist (Recommended for Cloud)"
echo "------------------------------------------------"
echo "1. Go to: https://cloud.mongodb.com/"
echo "2. Select your project 'learningDatabase'"
echo "3. Click 'Network Access' in the left sidebar"
echo "4. Click 'Add IP Address'"
echo "5. Either:"
echo "   - Click 'Add Current IP Address' (secure)"
echo "   - Or enter '0.0.0.0/0' to allow all IPs (less secure, but works everywhere)"
echo "6. Click 'Confirm'"
echo "7. Wait 1-2 minutes for changes to apply"
echo "8. Restart: npm run dev"
echo ""
echo "Option 2: Use Local MongoDB (Recommended for Development)"
echo "------------------------------------------------"
echo "If you have MongoDB installed locally:"
echo "1. Start MongoDB: sudo systemctl start mongod"
echo "2. Update .env.local:"
echo "   MONGODB_URI=mongodb://localhost:27017/password-manager"
echo "3. Restart: npm run dev"
echo ""
echo "Option 3: Install MongoDB Locally"
echo "------------------------------------------------"
echo "Ubuntu/Debian:"
echo "  sudo apt-get install mongodb"
echo "  sudo systemctl start mongodb"
echo ""
echo "Then update .env.local as shown in Option 2"
echo ""
